### ISSUE TITLE
Como usuario veo la explicación de cada uno de los ejes de mi visualización 

### ISSUE THREAD

**Issue by zoek1** [civica-digital/iris#11]

**Comment by ricalanis** [comment]
Liderazgo: Refleja la cantidad de aliados estratégicos, formales e informales, que cuenta la estrategia local de datos abiertos. Si el nivel de trabajo pendiente es alto, significa que debemos poner más atención en crear alianzas con oficiales de alto nivel, como el alcalde.
Fondos: Describe la cantidad de fondos que hacen falta para poder cubrir con las necesidades del proyecto de datos abiertos. Un nivel alto significa que se deben de buscar concretar más fuentes para sostenerlo.
Estructura Técnica: Define el trabajo necesario para cubrir las necesidades en estructura, tanto organizacional como de recursos, en el rubro de tecnología para apoyar la estrategia de datos abiertos.
Estatus de Apertura: Describe los avances en la apertura de datos. Muchas ciudades tiene pendiente el trabajo de cambiar de archivos físicos y PDF a tablas en excel o documentos abiertos. La red te apoyará con recursos que te facilitarán esta tarea.
Preparación de la Sociedad: ¿Estás incluyendo a la sociedad civil en tu estrategia de datos abiertos? Puedes mejorar esta categoría invitando a más organizaciones a apoyarte en el trabajo, o invitándolos a un evento donde se usen datos abiertos, como un datatón o un hackaton.
Entorno Legal: Esta categoría describe el avance que lleva tu localidad y su entorno para agregar a los datos abiertos en la normatividad vigente; Y el conocimiento que cuentan sobre las licencias para el consumo y distribución de información. Puedes mejorar esta sección con los recursos de la red en ambos conceptos.
Evaluación de Impacto: Tener mecanismos de autoevaluación sobre los avances de datos abiertos es crítico para saber si se está en el camino correcto. Mejora esta sección usando los recursos disponibles en la red e internacionalmente para hacer este ejercicio.
https://docs.google.com/document/d/1UXxk57MTcIhvj6x9e7MZkmB8UCwViCWyw9a9_BDljqk/edit
